<?php
    if( function_exists('acf_add_local_field_group') ):
        acf_add_local_field_group(array (
            'key' => 'group_5c86340e233f3',
            'title' => '[:vi]Đặt hẹn công ty[:]',
            'fields' => array (
                array (
                    'key' => 'field_5c863413c97b1',
                    'label' => '[:vi]Danh sách công ty[:en]Công ty khám theo lịch[:]',
                    'name' => 'schedule_company',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_5c8f43ed14639',
                            'label' => '[:vi]Công ty khám theo lịch[:en]Công ty[:]',
                            'name' => 'cong_ty',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_5c8f42ede2ce2',
                                    'label' => 'Công ty',
                                    'name' => 'name_of_company',
                                    'type' => 'group',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'layout' => 'table',
                                    'sub_fields' => array (
                                        array (
                                            'key' => 'field_5c9e3d5a52319',
                                            'label' => 'Show',
                                            'name' => 'show_on_site',
                                            'type' => 'checkbox',
                                            'instructions' => '[:en]show: Show lên website[:]',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '5',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'choices' => array (
                                                'show' => 'Show',
                                            ),
                                            'allow_custom' => 0,
                                            'save_custom' => 0,
                                            'default_value' => array (
                                            ),
                                            'layout' => 'vertical',
                                            'toggle' => 0,
                                            'return_format' => 'value',
                                        ),
                                        array (
                                            'key' => 'field_5c8f4318e2ce3',
                                            'label' => 'Tên công ty',
                                            'name' => 'company_name',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 1,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '10',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                        array (
                                            'key' => 'field_5c9e396e699df',
                                            'label' => 'Chọn ngày và buổi',
                                            'name' => 'all_day',
                                            'type' => 'repeater',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '70',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'collapsed' => '',
                                            'min' => 0,
                                            'max' => 0,
                                            'layout' => 'table',
                                            'button_label' => '',
                                            'sub_fields' => array (
                                                array (
                                                    'key' => 'field_5c9e3ad4699e0',
                                                    'label' => 'Ngày',
                                                    'name' => 'day',
                                                    'type' => 'date_picker',
                                                    'instructions' => '',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => array (
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ),
                                                    'display_format' => 'd/m/Y',
                                                    'return_format' => 'd/m/Y',
                                                    'first_day' => 1,
                                                ),
                                                array (
                                                    'key' => 'field_5ca99bb59f6be',
                                                    'label' => 'Sáng',
                                                    'name' => 'session_morning',
                                                    'type' => 'group',
                                                    'instructions' => '',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => array (
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ),
                                                    'layout' => 'block',
                                                    'sub_fields' => array (
                                                        array (
                                                            'key' => 'field_5ca99bd59f6bf',
                                                            'label' => 'Buổi',
                                                            'name' => 'text_morning',
                                                            'type' => 'checkbox',
                                                            'instructions' => '',
                                                            'required' => 0,
                                                            'conditional_logic' => 0,
                                                            'wrapper' => array (
                                                                'width' => '',
                                                                'class' => '',
                                                                'id' => '',
                                                            ),
                                                            'choices' => array (
                                                                'Sáng' => 'Sáng',
                                                            ),
                                                            'allow_custom' => 0,
                                                            'save_custom' => 0,
                                                            'default_value' => array (
                                                            ),
                                                            'layout' => 'vertical',
                                                            'toggle' => 0,
                                                            'return_format' => 'value',
                                                        ),
                                                        array (
                                                            'key' => 'field_5ca9b465e3075',
                                                            'label' => 'Số lượng',
                                                            'name' => 'amount_morning',
                                                            'type' => 'number',
                                                            'instructions' => '',
                                                            'required' => 0,
                                                            'conditional_logic' => 0,
                                                            'wrapper' => array (
                                                                'width' => '',
                                                                'class' => '',
                                                                'id' => '',
                                                            ),
                                                            'default_value' => '',
                                                            'placeholder' => '',
                                                            'prepend' => '',
                                                            'append' => '',
                                                            'min' => '',
                                                            'max' => 30,
                                                            'step' => '',
                                                        ),
                                                    ),
                                                ),
                                                array (
                                                    'key' => 'field_5ca99c249f6c1',
                                                    'label' => 'Chiều',
                                                    'name' => 'session_afternoon',
                                                    'type' => 'group',
                                                    'instructions' => '',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => array (
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ),
                                                    'layout' => 'block',
                                                    'sub_fields' => array (
                                                        array (
                                                            'key' => 'field_5ca99c369f6c2',
                                                            'label' => 'Chiều',
                                                            'name' => 'text_afternoon',
                                                            'type' => 'checkbox',
                                                            'instructions' => '',
                                                            'required' => 0,
                                                            'conditional_logic' => 0,
                                                            'wrapper' => array (
                                                                'width' => '',
                                                                'class' => '',
                                                                'id' => '',
                                                            ),
                                                            'choices' => array (
                                                                'Chiều' => 'Chiều',
                                                            ),
                                                            'allow_custom' => 0,
                                                            'save_custom' => 0,
                                                            'default_value' => array (
                                                            ),
                                                            'layout' => 'vertical',
                                                            'toggle' => 0,
                                                            'return_format' => 'value',
                                                        ),
                                                        array (
                                                            'key' => 'field_5ca99c4f9f6c3',
                                                            'label' => 'Số lượng',
                                                            'name' => 'amount_afternoon',
                                                            'type' => 'number',
                                                            'instructions' => '',
                                                            'required' => 0,
                                                            'conditional_logic' => 0,
                                                            'wrapper' => array (
                                                                'width' => '',
                                                                'class' => '',
                                                                'id' => '',
                                                            ),
                                                            'default_value' => '',
                                                            'placeholder' => '',
                                                            'prepend' => '',
                                                            'append' => '',
                                                            'min' => '',
                                                            'max' => 30,
                                                            'step' => '',
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                        array (
                                            'key' => 'field_5c8f43aee2ce6',
                                            'label' => 'Mã công ty',
                                            'name' => 'company_code',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 1,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '15',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_5c9e4c6b58cb8',
                            'label' => 'Công ty khám không cần lịch',
                            'name' => 'company_not_schedule',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_5c9e4ceb58cb9',
                                    'label' => 'Tên công ty',
                                    'name' => 'company_name',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array (
                                    'key' => 'field_5c9e4d1558cba',
                                    'label' => 'Số lượng',
                                    'name' => 'total_members',
                                    'type' => 'number',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'min' => '',
                                    'max' => '',
                                    'step' => '',
                                ),
                            ),
                        ),
                    ),
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'acf-options-danh-sach-cong-ty',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));
        
        endif;
        if( function_exists('acf_add_local_field_group') ):

            acf_add_local_field_group(array (
                'key' => 'group_5c83ce511cc6f',
                'title' => '[:vi]Dịch vụ + Bài viết khác[:]',
                'fields' => array (
                    array (
                        'key' => 'field_5ca8c07320ae8',
                        'label' => 'Dịch vụ',
                        'name' => 'services',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5c83ed1687d4a',
                                'label' => 'Tên dịch vụ',
                                'name' => 'name_of_service',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5c87752e07023',
                                'label' => 'Mô tả',
                                'name' => 'description_of_service',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                            array (
                                'key' => 'field_5c83cf9d2e3a5',
                                'label' => '[:vi]Tất cả tab[:en]Tab[:]',
                                'name' => 'tab',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5c83cfac2e3a6',
                                        'label' => 'Tên',
                                        'name' => 'ten',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_5c83cfb22e3a7',
                                        'label' => 'Link',
                                        'name' => 'link',
                                        'type' => 'repeater',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'collapsed' => '',
                                        'min' => 0,
                                        'max' => 0,
                                        'layout' => 'table',
                                        'button_label' => '',
                                        'sub_fields' => array (
                                            array (
                                                'key' => 'field_5c83cfcf89d97',
                                                'label' => '[:vi]Link to[:en]Link[:]',
                                                'name' => 'link_to',
                                                'type' => 'post_object',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array (
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'post_type' => array (
                                                ),
                                                'taxonomy' => array (
                                                ),
                                                'allow_null' => 0,
                                                'multiple' => 0,
                                                'return_format' => 'object',
                                                'ui' => 1,
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array (
                        'key' => 'field_5ca8c0b7e5285',
                        'label' => 'Các bài viết khác',
                        'name' => 'related_posts',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5caf71b4dac3a',
                                'label' => 'Bài viết',
                                'name' => 'post_difference',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5caf71eddac3b',
                                        'label' => '[:vi]Đường dẫn bài viết[:en]Tên[:]',
                                        'name' => 'name_of_post',
                                        'type' => 'post_object',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'post_type' => array (
                                            0 => 'dich_vu',
                                            1 => 'post',
                                            2 => 'hoat_dong',
                                            3 => 'gioi_thieu_khoa',
                                            4 => 'page',
                                        ),
                                        'taxonomy' => array (
                                        ),
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'return_format' => 'object',
                                        'ui' => 1,
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array (
                        'key' => 'field_5cb205db0d0c0',
                        'label' => 'Live support',
                        'name' => 'live_support',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5cb205f80d0c1',
                                'label' => 'Icon',
                                'name' => 'icon',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5cb2060e0d0c2',
                                'label' => 'Tiêu đề',
                                'name' => 'title_live',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5cb206220d0c3',
                                'label' => 'Đường dẫn',
                                'name' => 'link_live',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                            ),
                        ),
                    ),
                ),
                'location' => array (
                    array (
                        array (
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'acf-options-dich-vu',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => 1,
                'description' => '',
            ));
            
            endif;