<?php
    if( function_exists('acf_add_local_field_group') ):
        acf_add_local_field_group(array (
            'key' => 'group_5cee8e70f27c3',
            'title' => '[:vi]External link [:]',
            'fields' => array (
                array (
                    'key' => 'field_5cee8e860215c',
                    'label' => 'External link',
                    'name' => 'external_link',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'page',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));
        
        acf_add_local_field_group(array (
            'key' => 'group_5df9f1ee24ca8',
            'title' => '[:vi]Background[:]',
            'fields' => array (
                array (
                    'key' => 'field_5df9f1f52fe50',
                    'label' => 'Background',
                    'name' => 'background_breadcrumb',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'full',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'page',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));

        acf_add_local_field_group(array (
            'key' => 'group_5c86340e233f3',
            'title' => '[:vi]Đặt hẹn công ty[:]',
            'fields' => array (
                array (
                    'key' => 'field_5c863413c97b1',
                    'label' => '[:vi]Danh sách công ty[:en]Công ty khám theo lịch[:]',
                    'name' => 'schedule_company',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_5c8f43ed14639',
                            'label' => '[:vi]Công ty khám theo lịch[:en]Công ty[:]',
                            'name' => 'cong_ty',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_5c8f42ede2ce2',
                                    'label' => 'Công ty',
                                    'name' => 'name_of_company',
                                    'type' => 'group',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'layout' => 'table',
                                    'sub_fields' => array (
                                        array (
                                            'key' => 'field_5c9e3d5a52319',
                                            'label' => 'Show',
                                            'name' => 'show_on_site',
                                            'type' => 'checkbox',
                                            'instructions' => '[:en]show: Show lên website[:]',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '5',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'choices' => array (
                                                'show' => 'Show',
                                            ),
                                            'allow_custom' => 0,
                                            'save_custom' => 0,
                                            'default_value' => array (
                                            ),
                                            'layout' => 'vertical',
                                            'toggle' => 0,
                                            'return_format' => 'value',
                                        ),
                                        array (
                                            'key' => 'field_5c8f4318e2ce3',
                                            'label' => 'Tên công ty',
                                            'name' => 'company_name',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 1,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '10',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                        array (
                                            'key' => 'field_5c9e396e699df',
                                            'label' => 'Chọn ngày và buổi',
                                            'name' => 'all_day',
                                            'type' => 'repeater',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '70',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'collapsed' => '',
                                            'min' => 0,
                                            'max' => 0,
                                            'layout' => 'table',
                                            'button_label' => '',
                                            'sub_fields' => array (
                                                array (
                                                    'key' => 'field_5c9e3ad4699e0',
                                                    'label' => 'Ngày',
                                                    'name' => 'day',
                                                    'type' => 'date_picker',
                                                    'instructions' => '',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => array (
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ),
                                                    'display_format' => 'd/m/Y',
                                                    'return_format' => 'd/m/Y',
                                                    'first_day' => 1,
                                                ),
                                                array (
                                                    'key' => 'field_5ca99bb59f6be',
                                                    'label' => 'Sáng',
                                                    'name' => 'session_morning',
                                                    'type' => 'group',
                                                    'instructions' => '',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => array (
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ),
                                                    'layout' => 'block',
                                                    'sub_fields' => array (
                                                        array (
                                                            'key' => 'field_5ca99bd59f6bf',
                                                            'label' => 'Buổi',
                                                            'name' => 'text_morning',
                                                            'type' => 'checkbox',
                                                            'instructions' => '',
                                                            'required' => 0,
                                                            'conditional_logic' => 0,
                                                            'wrapper' => array (
                                                                'width' => '',
                                                                'class' => '',
                                                                'id' => '',
                                                            ),
                                                            'choices' => array (
                                                                'Sáng' => 'Sáng',
                                                            ),
                                                            'allow_custom' => 0,
                                                            'save_custom' => 0,
                                                            'default_value' => array (
                                                            ),
                                                            'layout' => 'vertical',
                                                            'toggle' => 0,
                                                            'return_format' => 'value',
                                                        ),
                                                        array (
                                                            'key' => 'field_5ca9b465e3075',
                                                            'label' => 'Số lượng',
                                                            'name' => 'amount_morning',
                                                            'type' => 'number',
                                                            'instructions' => '',
                                                            'required' => 0,
                                                            'conditional_logic' => 0,
                                                            'wrapper' => array (
                                                                'width' => '',
                                                                'class' => '',
                                                                'id' => '',
                                                            ),
                                                            'default_value' => '',
                                                            'placeholder' => '',
                                                            'prepend' => '',
                                                            'append' => '',
                                                            'min' => '',
                                                            'max' => 30,
                                                            'step' => '',
                                                        ),
                                                    ),
                                                ),
                                                array (
                                                    'key' => 'field_5ca99c249f6c1',
                                                    'label' => 'Chiều',
                                                    'name' => 'session_afternoon',
                                                    'type' => 'group',
                                                    'instructions' => '',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => array (
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ),
                                                    'layout' => 'block',
                                                    'sub_fields' => array (
                                                        array (
                                                            'key' => 'field_5ca99c369f6c2',
                                                            'label' => 'Chiều',
                                                            'name' => 'text_afternoon',
                                                            'type' => 'checkbox',
                                                            'instructions' => '',
                                                            'required' => 0,
                                                            'conditional_logic' => 0,
                                                            'wrapper' => array (
                                                                'width' => '',
                                                                'class' => '',
                                                                'id' => '',
                                                            ),
                                                            'choices' => array (
                                                                'Chiều' => 'Chiều',
                                                            ),
                                                            'allow_custom' => 0,
                                                            'save_custom' => 0,
                                                            'default_value' => array (
                                                            ),
                                                            'layout' => 'vertical',
                                                            'toggle' => 0,
                                                            'return_format' => 'value',
                                                        ),
                                                        array (
                                                            'key' => 'field_5ca99c4f9f6c3',
                                                            'label' => 'Số lượng',
                                                            'name' => 'amount_afternoon',
                                                            'type' => 'number',
                                                            'instructions' => '',
                                                            'required' => 0,
                                                            'conditional_logic' => 0,
                                                            'wrapper' => array (
                                                                'width' => '',
                                                                'class' => '',
                                                                'id' => '',
                                                            ),
                                                            'default_value' => '',
                                                            'placeholder' => '',
                                                            'prepend' => '',
                                                            'append' => '',
                                                            'min' => '',
                                                            'max' => 30,
                                                            'step' => '',
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                        array (
                                            'key' => 'field_5c8f43aee2ce6',
                                            'label' => 'Mã công ty',
                                            'name' => 'company_code',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 1,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '15',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_5c9e4c6b58cb8',
                            'label' => 'Công ty khám không cần lịch',
                            'name' => 'company_not_schedule',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_5c9e4ceb58cb9',
                                    'label' => 'Tên công ty',
                                    'name' => 'company_name',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array (
                                    'key' => 'field_5c9e4d1558cba',
                                    'label' => 'Số lượng',
                                    'name' => 'total_members',
                                    'type' => 'number',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'min' => '',
                                    'max' => '',
                                    'step' => '',
                                ),
                            ),
                        ),
                    ),
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'acf-options-danh-sach-cong-ty',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));
        
        endif;
        if( function_exists('acf_add_local_field_group') ):

            acf_add_local_field_group(array (
                'key' => 'group_5c83ce511cc6f',
                'title' => '[:vi]Dịch vụ[:]',
                'fields' => array (
                    array (
                        'key' => 'field_5c83ed1687d4a',
                        'label' => 'Tên dịch vụ',
                        'name' => 'name_of_service',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5dfc7d29f2596',
                        'label' => 'Tiện ích',
                        'name' => 'utilities',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 6,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5dfc7d7bf2597',
                                'label' => 'Tiện ích',
                                'name' => 'utilities_small',
                                'type' => 'post_object',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'post_type' => array (
                                ),
                                'taxonomy' => array (
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'return_format' => 'object',
                                'ui' => 1,
                            ),
                        ),
                    ),
                    array (
                        'key' => 'field_5df7a66cb898d',
                        'label' => 'Đặt hẹn',
                        'name' => 'schedule',
                        'type' => 'flexible_content',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layouts' => array (
                            '5df7a72e45999' => array (
                                'key' => '5df7a72e45999',
                                'name' => 'them_cot',
                                'label' => 'Thêm cột',
                                'display' => 'table',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5df8ebf9008ac',
                                        'label' => 'Title',
                                        'name' => 'title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_5df9c92fff861',
                                        'label' => 'link',
                                        'name' => 'link',
                                        'type' => 'post_object',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'post_type' => array (
                                        ),
                                        'taxonomy' => array (
                                        ),
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'return_format' => 'object',
                                        'ui' => 1,
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                        ),
                        'button_label' => 'Add Row',
                        'min' => 2,
                        'max' => 4,
                    ),
                    array (
                        'key' => 'field_5c87752e07023',
                        'label' => 'Mô tả',
                        'name' => 'description_of_service',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                    array (
                        'key' => 'field_5c83cf9d2e3a5',
                        'label' => '[:vi]Tất cả tab[:en]Tab[:]',
                        'name' => 'tab',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5c83cfac2e3a6',
                                'label' => 'Tên',
                                'name' => 'ten',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5c83cfb22e3a7',
                                'label' => 'Link',
                                'name' => 'link',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '80',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5ce96f8002999',
                                        'label' => 'Choose post',
                                        'name' => 'choose_post',
                                        'type' => 'flexible_content',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'layouts' => array (
                                            '5ce96fad7ea39' => array (
                                                'key' => '5ce96fad7ea39',
                                                'name' => 'internal',
                                                'label' => 'internal',
                                                'display' => 'block',
                                                'sub_fields' => array (
                                                    array (
                                                        'key' => 'field_5ce96fdf0299a',
                                                        'label' => 'internal',
                                                        'name' => 'internal',
                                                        'type' => 'post_object',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array (
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'post_type' => array (
                                                            0 => 'post',
                                                            1 => 'cham_soc_khach_hang',
                                                            2 => 'hoat_dong',
                                                        ),
                                                        'taxonomy' => array (
                                                        ),
                                                        'allow_null' => 0,
                                                        'multiple' => 0,
                                                        'return_format' => 'object',
                                                        'ui' => 1,
                                                    ),
                                                ),
                                                'min' => '',
                                                'max' => '',
                                            ),
                                            '5ce970340299b' => array (
                                                'key' => '5ce970340299b',
                                                'name' => 'external',
                                                'label' => 'external',
                                                'display' => 'block',
                                                'sub_fields' => array (
                                                    array (
                                                        'key' => 'field_5ce970420299c',
                                                        'label' => 'title',
                                                        'name' => 'title',
                                                        'type' => 'text',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array (
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'default_value' => '',
                                                        'placeholder' => '',
                                                        'prepend' => '',
                                                        'append' => '',
                                                        'maxlength' => '',
                                                    ),
                                                    array (
                                                        'key' => 'field_5ce9704e0299d',
                                                        'label' => 'description',
                                                        'name' => 'description',
                                                        'type' => 'textarea',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array (
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'default_value' => '',
                                                        'placeholder' => '',
                                                        'maxlength' => '',
                                                        'rows' => '',
                                                        'new_lines' => '',
                                                    ),
                                                    array (
                                                        'key' => 'field_5ce970600299e',
                                                        'label' => 'background',
                                                        'name' => 'background',
                                                        'type' => 'image',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array (
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'return_format' => 'array',
                                                        'preview_size' => 'thumbnail',
                                                        'library' => 'all',
                                                        'min_width' => '',
                                                        'min_height' => '',
                                                        'min_size' => '',
                                                        'max_width' => '',
                                                        'max_height' => '',
                                                        'max_size' => '',
                                                        'mime_types' => '',
                                                    ),
                                                    array (
                                                        'key' => 'field_5ce9706e0299f',
                                                        'label' => 'link',
                                                        'name' => 'link',
                                                        'type' => 'url',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array (
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'default_value' => '',
                                                        'placeholder' => '',
                                                    ),
                                                ),
                                                'min' => '',
                                                'max' => '',
                                            ),
                                        ),
                                        'button_label' => 'Add Row',
                                        'min' => '',
                                        'max' => '',
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array (
                        'key' => 'field_5ca8c0b7e5285',
                        'label' => 'Các bài viết khác',
                        'name' => 'related_posts',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5caf71b4dac3a',
                                'label' => 'Bài viết',
                                'name' => 'post_difference',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5caf71eddac3b',
                                        'label' => '[:vi]Đường dẫn bài viết[:en]Tên[:]',
                                        'name' => 'name_of_post',
                                        'type' => 'post_object',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'post_type' => array (
                                            0 => 'cham_soc_khach_hang',
                                            1 => 'post',
                                            2 => 'hoat_dong',
                                            4 => 'page',
                                        ),
                                        'taxonomy' => array (
                                        ),
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'return_format' => 'object',
                                        'ui' => 1,
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array (
                    'key' => 'field_5cb205db0d0c0',
                    'label' => 'Live support',
                    'name' => 'live_support',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => '',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_5cb205f80d0c1',
                            'label' => 'Icon',
                            'name' => 'icon',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5cb2060e0d0c2',
                            'label' => 'Tiêu đề',
                            'name' => 'title_live',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5cb206220d0c3',
                            'label' => 'Đường dẫn',
                            'name' => 'link_live',
                            'type' => 'link',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                        ),
                    ),
                ),
                ),
                'location' => array (
                    array (
                        array (
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'acf-options-dich-vu',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => 1,
                'description' => '',
            ));

            acf_add_local_field_group(array (
                'key' => 'group_5c852439ba379',
                'title' => '[:vi]Mô tả section[:]',
                'fields' => array (
                    array (
                        'key' => 'field_5c87269b6c50f',
                        'label' => 'Tiện ích nổi bật',
                        'name' => 'featured_gadgets',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5c8727436c510',
                                'label' => 'Tiêu đề',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5c87274c6c511',
                                'label' => 'Mô tả',
                                'name' => 'description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                        ),
                    ),
                    array (
                        'key' => 'field_5c8524b15264e',
                        'label' => 'Chuyên khoa',
                        'name' => 'specialist',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5c872a656c512',
                                'label' => 'Tiêu đề',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5c872a6e6c513',
                                'label' => 'Mô tả',
                                'name' => 'description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                        ),
                    ),
                    array (
                        'key' => 'field_5c872a9e6c514',
                        'label' => 'Hoạt động',
                        'name' => 'active',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5c872ab06c515',
                                'label' => 'Tiêu đề',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5c872ab96c516',
                                'label' => 'Mô tả',
                                'name' => 'description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                        ),
                    ),
                    array (
                        'key' => 'field_5c8524435264d',
                        'label' => 'Hình ảnh',
                        'name' => 'image_section',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5c872ae06c517',
                                'label' => 'Tiêu đề',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5c872aea6c518',
                                'label' => 'Mô tả',
                                'name' => 'description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                        ),
                    ),
                    array (
                        'key' => 'field_5c8cb880e04d2',
                        'label' => 'Video giới thiệu',
                        'name' => 'video_intro',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5c8cb92de04d3',
                                'label' => 'Tiêu đề',
                                'name' => 'video_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5c8cb942e04d4',
                                'label' => 'Mô tả',
                                'name' => 'video_description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'new_lines' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'rows' => '',
                            ),
                            array (
                                'key' => 'field_5c8cb95ce04d5',
                                'label' => 'Link',
                                'name' => 'video_link',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => '',
                                'collapsed' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5c8cba871538b',
                                        'label' => 'Link',
                                        'name' => 'links',
                                        'type' => 'link',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array (
                        'key' => 'field_5d07bd0f47799',
                        'label' => 'Cảm nhận khách hàng',
                        'name' => 'cam_nhan_khach_hang',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5d07bd2b4779a',
                                'label' => 'Tiêu đề',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5d07bd354779b',
                                'label' => 'Mô tả',
                                'name' => 'description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                        ),
                    ),
                ),
                'location' => array (
                    array (
                        array (
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'acf-options-tieu-de',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => 1,
                'description' => '',
            ));
            
            endif;
            if( function_exists('acf_add_local_field_group') ):

                acf_add_local_field_group(array (
                    'key' => 'group_5d99dd49a97a1',
                    'title' => '[:vi]văn bản[:]',
                    'fields' => array (
                        array (
                            'key' => 'field_5d99dd4f4cee8',
                            'label' => 'Column 01',
                            'name' => 'column_01',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'row',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_5d99dd5c4cee9',
                                    'label' => 'Title',
                                    'name' => 'title',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array (
                                    'key' => 'field_5d99dd794ceea',
                                    'label' => 'Nội dung',
                                    'name' => 'desc',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'collapsed' => '',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'table',
                                    'button_label' => '',
                                    'sub_fields' => array (
                                        array (
                                            'key' => 'field_5d99dd894ceeb',
                                            'label' => 'Nội dung',
                                            'name' => 'description',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => 4,
                                            'new_lines' => '',
                                        ),
                                        array (
                                            'key' => 'field_5d99deb017d97',
                                            'label' => 'Thời gian',
                                            'name' => 'createAt',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                    ),
                                ),
                                array (
                                    'key' => 'field_5d99ddb64ceed',
                                    'label' => 'Link',
                                    'name' => 'link',
                                    'type' => 'url',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_5d99ddc74ceee',
                            'label' => 'Column 02',
                            'name' => 'column_02',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'row',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_5d99ddc74ceef',
                                    'label' => 'Title',
                                    'name' => 'title',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array (
                                    'key' => 'field_5d99ddc74cef0',
                                    'label' => 'Nội dung',
                                    'name' => 'desc',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'collapsed' => '',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'table',
                                    'button_label' => '',
                                    'sub_fields' => array (
                                        array (
                                            'key' => 'field_5d99ddc74cef1',
                                            'label' => 'Nội dung',
                                            'name' => 'description',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => 4,
                                            'new_lines' => '',
                                        ),
                                        array (
                                            'key' => 'field_5d99dec417d98',
                                            'label' => 'Thời gian',
                                            'name' => 'createAt',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                    ),
                                ),
                                array (
                                    'key' => 'field_5d99ddc74cef3',
                                    'label' => 'Link',
                                    'name' => 'link',
                                    'type' => 'url',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_5d99ddd34cef4',
                            'label' => 'Column 03',
                            'name' => 'column_03',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'row',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_5d99ddd34cef5',
                                    'label' => 'Title',
                                    'name' => 'title',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array (
                                    'key' => 'field_5d99ddd34cef6',
                                    'label' => 'Nội dung',
                                    'name' => 'desc',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'collapsed' => '',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'table',
                                    'button_label' => '',
                                    'sub_fields' => array (
                                        array (
                                            'key' => 'field_5d99ddd34cef7',
                                            'label' => 'Nội dung',
                                            'name' => 'description',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => 4,
                                            'new_lines' => '',
                                        ),
                                        array (
                                            'key' => 'field_5d99ded417d99',
                                            'label' => 'Thời gian',
                                            'name' => 'createAt',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                    ),
                                ),
                                array (
                                    'key' => 'field_5d99ddd34cef9',
                                    'label' => 'Link',
                                    'name' => 'link',
                                    'type' => 'url',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                ),
                            ),
                        ),
                    ),
                    'location' => array (
                        array (
                            array (
                                'param' => 'page',
                                'operator' => '==',
                                'value' => '124',
                            ),
                        ),
                    ),
                    'menu_order' => 0,
                    'position' => 'normal',
                    'style' => 'default',
                    'label_placement' => 'top',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => '',
                    'active' => 1,
                    'description' => '',
                ));
                
                endif;