<?php
    if( function_exists('acf_add_local_field_group') ):

        acf_add_local_field_group(array (
            'key' => 'group_5c86340e233f3',
            'title' => '[:vi]Đặt hẹn công ty[:]',
            'fields' => array (
                array (
                    'key' => 'field_5c863413c97b1',
                    'label' => '[:vi]Danh sách công ty[:en]Công ty khám theo lịch[:]',
                    'name' => 'schedule_company',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_5c8f43ed14639',
                            'label' => '[:vi]Công ty khám theo lịch[:en]Công ty[:]',
                            'name' => 'cong_ty',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_5c8f42ede2ce2',
                                    'label' => 'Công ty',
                                    'name' => 'name_of_company',
                                    'type' => 'group',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'layout' => 'table',
                                    'sub_fields' => array (
                                        array (
                                            'key' => 'field_5c9e3d5a52319',
                                            'label' => 'Show',
                                            'name' => 'show_on_site',
                                            'type' => 'checkbox',
                                            'instructions' => '[:en]show: Show lên website[:]',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '10',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'choices' => array (
                                                'show' => 'Show',
                                            ),
                                            'allow_custom' => 0,
                                            'save_custom' => 0,
                                            'default_value' => array (
                                            ),
                                            'layout' => 'vertical',
                                            'toggle' => 0,
                                            'return_format' => 'value',
                                        ),
                                        array (
                                            'key' => 'field_5c8f4318e2ce3',
                                            'label' => 'Tên công ty',
                                            'name' => 'company_name',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 1,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                        array (
                                            'key' => 'field_5c9e396e699df',
                                            'label' => 'Chọn ngày và buổi',
                                            'name' => 'all_day',
                                            'type' => 'repeater',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'collapsed' => '',
                                            'min' => 0,
                                            'max' => 0,
                                            'layout' => 'table',
                                            'button_label' => '',
                                            'sub_fields' => array (
                                                array (
                                                    'key' => 'field_5c9e3ad4699e0',
                                                    'label' => 'Ngày',
                                                    'name' => 'day',
                                                    'type' => 'date_picker',
                                                    'instructions' => '',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => array (
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ),
                                                    'display_format' => 'd/m/Y',
                                                    'return_format' => 'd/m/Y',
                                                    'first_day' => 1,
                                                ),
                                                array (
                                                    'key' => 'field_5c9e3aed699e1',
                                                    'label' => 'Buổi',
                                                    'name' => 'session',
                                                    'type' => 'checkbox',
                                                    'instructions' => '',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => array (
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ),
                                                    'choices' => array (
                                                        'Sáng' => 'Sáng',
                                                        'Chiều' => 'Chiều',
                                                    ),
                                                    'allow_custom' => 0,
                                                    'save_custom' => 0,
                                                    'default_value' => array (
                                                    ),
                                                    'layout' => 'vertical',
                                                    'toggle' => 0,
                                                    'return_format' => 'value',
                                                ),
                                            ),
                                        ),
                                        array (
                                            'key' => 'field_5c8f43aee2ce6',
                                            'label' => 'Mã công ty',
                                            'name' => 'company_code',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 1,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_5c9e4c6b58cb8',
                            'label' => 'Công ty khám không cần lịch',
                            'name' => 'company_not_schedule',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_5c9e4ceb58cb9',
                                    'label' => 'Tên công ty',
                                    'name' => 'company_name',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array (
                                    'key' => 'field_5c9e4d1558cba',
                                    'label' => 'Số lượng',
                                    'name' => 'total_members',
                                    'type' => 'number',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'min' => '',
                                    'max' => '',
                                    'step' => '',
                                ),
                            ),
                        ),
                    ),
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'acf-options-danh-sach-cong-ty',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));
        
        endif;